engines:
  cppcheck:
    enabled: true
    configuration:
      arguments:
        - "--library=std.cfg"
        - "--check-config"
        - "--enable=all"
        - "--std=c99"
        - "--inline-suppr"
        - "-Iinclude"
        - "-Itools/codacy_shims/ps2sdk"
        - "-Itools/codacy_shims/stdlib"
      suppressions:
        - cppcheck-suppressions.txt
exclude_paths:
  - src/util_safeio.c
  - include/cppcheck_stubs/**
