engines:
  cppcheck:
    enabled: true
    configuration:
      suppressions:
        - cppcheck-suppressions.txt
      suppress:
        - missingIncludeSystem
        - missingInclude
exclude_paths:
  - src/util_safeio.c
